apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service1
  name: service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service1
    spec:
      containers:
        - image: public.ecr.aws/n8u7z3z1/service1:service1
          name: service1
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 4000
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    run: service1
spec:
  ports:
    - port: 4000
      protocol: TCP
  selector:
    app: service1
  type: NodePort
